// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "openapi": "3.0.0",
    "info": {
        "title": "{{.Title}}",
        "description": "{{escape .Description}}",
        "version": "{{.Version}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.example.com/support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        }
    },
    "servers": [
        {
            "url": "http://{{.Host}}{{.BasePath}}"
        }
    ],
    "paths": {
        "/{storage_name}/{relative_path}/objects/{object_id}/content": {
            "get": {
                "summary": "Download file from storage",
                "description": "Download a file from specified storage path",
                "tags": [
                    "Storage"
                ],
                "parameters": [
                    {
                        "name": "storage_name",
                        "in": "path",
                        "description": "Storage name",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "relative_path",
                        "in": "path",
                        "description": "Relative path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "object_id",
                        "in": "path",
                        "description": "Object ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/octet-stream": {
                                "schema": {
                                    "type": "string",
                                    "format": "binary"
                                }
                            }
                        },
                        "headers": {
                            "Content-Disposition": {
                                "description": "Инструкция браузеру сохранить файл с оригинальным именем",
                                "schema": {
                                    "type": "string",
                                    "default": "attachment; filename=\"original-filename.ext\"",
                                    "example": "attachment; filename=\"Sound.mp3\""
                                }
                            },
                            "Content-Type": {
                                "description": "MIME-тип возвращаемого файла",
                                "schema": {
                                    "type": "string",
                                    "default": "application/octet-stream",
                                    "example": "audio/mpeg"
                                }
                            },
                            "Date": {
                                "description": "Дата ответа сервера",
                                "schema": {
                                    "type": "string",
                                    "format": "date-time",
                                    "example": "Sat, 30 Aug 2025 09:33:22 GMT"
                                }
                            },
                            "Transfer-Encoding": {
                                "description": "Тип передачи данных",
                                "schema": {
                                    "type": "string",
                                    "default": "chunked",
                                    "example": "chunked"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/server.errorResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/server.errorResponse"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Upload file to storage",
                "description": "Upload a file to specified storage path",
                "tags": [
                    "Storage"
                ],
                "parameters": [
                    {
                        "name": "storage_name",
                        "in": "path",
                        "description": "Storage name",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "relative_path",
                        "in": "path",
                        "description": "Relative path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "object_id",
                        "in": "path",
                        "description": "Object ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "file": {
                                        "type": "string",
                                        "format": "binary",
                                        "description": "File to upload"
                                    }
                                },
                                "required": ["file"]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Upload successful",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/server.objectResponse"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/server.errorResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/server.errorResponse"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "server.objectResponse": {
                "type": "object",
                "properties": {
                    "status": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "size_mb": {
                        "type": "integer"
                    }
                }
            },
            "server.errorResponse": {
                "type": "object",
                "properties": {
                    "error": {
                        "type": "string"
                    },
                    "code": {
                        "type": "integer"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "S3 Multiclient API",
	Description:      "API for uploading and downloading files from S3 storage (MinIO, Ceph) ",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}